wandb_version: 1

project:
  desc: null
  value: CORL
group:
  desc: null
  value: SAC-N
name:
  desc: null
  value: SAC-N-MiniGrid-FourRooms-v1-c8e3b98d
hidden_dim:
  desc: null
  value: 256
num_critics:
  desc: null
  value: 10
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.005
actor_learning_rate:
  desc: null
  value: 0.0003
critic_learning_rate:
  desc: null
  value: 0.0003
alpha_learning_rate:
  desc: null
  value: 0.0003
max_action:
  desc: null
  value: 1.0
buffer_size:
  desc: null
  value: 1000000
env_name:
  desc: null
  value: MiniGrid-FourRooms-v1
batch_size:
  desc: null
  value: 256
num_epochs:
  desc: null
  value: 3000
num_updates_on_epoch:
  desc: null
  value: 1000
normalize_reward:
  desc: null
  value: false
eval_episodes:
  desc: null
  value: 10
eval_every:
  desc: null
  value: 5
checkpoints_path:
  desc: null
  value: null
deterministic_torch:
  desc: null
  value: false
train_seed:
  desc: null
  value: 10
eval_seed:
  desc: null
  value: 42
log_every:
  desc: null
  value: 100
device:
  desc: null
  value: cpu
_wandb:
  desc: null
  value:
    python_version: 3.12.0
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714901543.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.12.0
      5: 0.16.6
      8:
      - 4
      - 5
      10:
      - 3
      13: darwin-arm64
